= PostgreSQL logger foreign data wrapper

== Requirements

* PostgreSQL 9.3
* `csvlog` in `log_destination`
* `logging_collector = on`
* `log_filename = 'postgresql.log'`


== Overview

----
CREATE EXTENSION pglog;
----

The extension is responsible for:

----
CREATE SERVER pglog_server FOREIGN DATA WRAPPER pglog NO VALIDATOR;

CREATE FOREIGN TABLE log
(
  log_time timestamp(3) with time zone,
  user_name text,
  database_name text,
  process_id integer,
  connection_from text,
  session_id text,
  session_line_num bigint,
  command_tag text,
  session_start_time timestamp with time zone,
  virtual_transaction_id text,
  transaction_id bigint,
  error_severity text,
  sql_state_code text,
  message text,
  detail text,
  hint text,
  internal_query text,
  internal_query_pos integer,
  context text,
  query text,
  query_pos integer,
  location text,
  application_name text
) SERVER pglog_server;

----

The extension will map a foreign table, named `log`, to all the
CSV files contained in the `log_directory` and using the `log_filename` rules.

== Initial limitations

* Support for CSV log
* No support for severity level data type (allows WHERE error_severity >= 'INFO')
* No support for compressed files
* No support for condition push down in WHERE queries
* No support for ANALYSE
* No support for date partitioning
* No support for security (full control for superusers, limited to normal users
footnote:[User control can be limited to string matching or current roles in the database server])

== Links

* http://www.postgresql.org/docs/9.3/static/runtime-config-logging.html#RUNTIME-CONFIG-LOGGING-CSVLOG
